import pandas as pd

if __name__ == '__main__':
    print("Performing post-process")
    real_data = pd.read_csv('Power_grid_real_data.csv').reset_index(drop=True)
    synthetic_data = pd.read_csv("Power_grid_synthetic_data.csv").sample(len(real_data))
    # Extra column generated by pandas
    del synthetic_data['Unnamed: 0']
    ####################################################################
    # For those columns which have lots of 0 in real dataset, but no 0 in synthetic dataset, we set a threshold for 0 value
    synthetic_data['R1-PA8:VH'] = synthetic_data['R1-PA8:VH'].apply(lambda x: 0 if (x < 0.3 and x > -0.3) else x)
    synthetic_data['R1-PM8:V'] = synthetic_data['R1-PM8:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R1-PA9:VH'] = synthetic_data['R1-PA9:VH'].apply(lambda x: 0 if (x < 1.3 and x > -0.5) else x)
    synthetic_data['R1-PM9:V'] = synthetic_data['R1-PM9:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R1-PA11:IH'] = synthetic_data['R1-PA11:IH'].apply(
        lambda x: 0 if (x < 0.06 and x > -0.02) else x)
    synthetic_data['R1-PM11:I'] = synthetic_data['R1-PM11:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R1-PA12:IH'] = synthetic_data['R1-PA12:IH'].apply(
        lambda x: 0 if (x < 0.14 and x > -0.02) else x)
    synthetic_data['R1-PM12:I'] = synthetic_data['R1-PM12:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R1:DF'] = synthetic_data['R1:DF'].apply(lambda x: 0 if (x < 0.01 and x > -0.01) else x)

    synthetic_data['R2-PA8:VH'] = synthetic_data['R2-PA8:VH'].apply(lambda x: 0 if (x < 0.3 and x > -0.3) else x)
    synthetic_data['R2-PM8:V'] = synthetic_data['R2-PM8:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R2-PA9:VH'] = synthetic_data['R2-PA9:VH'].apply(lambda x: 0 if (x < 1.3 and x > -0.5) else x)
    synthetic_data['R2-PM9:V'] = synthetic_data['R2-PM9:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R2-PA11:IH'] = synthetic_data['R2-PA11:IH'].apply(
        lambda x: 0 if (x < 0.06 and x > -0.02) else x)
    synthetic_data['R2-PM11:I'] = synthetic_data['R2-PM11:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R2-PA12:IH'] = synthetic_data['R2-PA12:IH'].apply(
        lambda x: 0 if (x < 0.14 and x > -0.02) else x)
    synthetic_data['R2-PM12:I'] = synthetic_data['R2-PM12:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R2:DF'] = synthetic_data['R2:DF'].apply(lambda x: 0 if (x < 0.01 and x > -0.01) else x)

    synthetic_data['R3-PA8:VH'] = synthetic_data['R3-PA8:VH'].apply(lambda x: 0 if (x < 0.3 and x > -0.3) else x)
    synthetic_data['R3-PM8:V'] = synthetic_data['R3-PM8:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R3-PA9:VH'] = synthetic_data['R3-PA9:VH'].apply(lambda x: 0 if (x < 1.3 and x > -0.5) else x)
    synthetic_data['R3-PM9:V'] = synthetic_data['R3-PM9:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R3-PA11:IH'] = synthetic_data['R3-PA11:IH'].apply(
        lambda x: 0 if (x < 0.06 and x > -0.02) else x)
    synthetic_data['R3-PM11:I'] = synthetic_data['R3-PM11:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R3-PA12:IH'] = synthetic_data['R3-PA12:IH'].apply(
        lambda x: 0 if (x < 0.14 and x > -0.02) else x)
    synthetic_data['R3-PM12:I'] = synthetic_data['R3-PM12:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R3:DF'] = synthetic_data['R3:DF'].apply(lambda x: 0 if (x < 0.01 and x > -0.01) else x)

    synthetic_data['R4-PA8:VH'] = synthetic_data['R4-PA8:VH'].apply(lambda x: 0 if (x < 0.3 and x > -0.3) else x)
    synthetic_data['R4-PM8:V'] = synthetic_data['R4-PM8:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R4-PA9:VH'] = synthetic_data['R4-PA9:VH'].apply(lambda x: 0 if (x < 1.3 and x > -0.5) else x)
    synthetic_data['R4-PM9:V'] = synthetic_data['R4-PM9:V'].apply(lambda x: 0 if (x < 1000) else x)
    synthetic_data['R4-PA11:IH'] = synthetic_data['R4-PA11:IH'].apply(
        lambda x: 0 if (x < 0.06 and x > -0.02) else x)
    synthetic_data['R4-PM11:I'] = synthetic_data['R4-PM11:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R4-PA12:IH'] = synthetic_data['R4-PA12:IH'].apply(
        lambda x: 0 if (x < 0.14 and x > -0.02) else x)
    synthetic_data['R4-PM12:I'] = synthetic_data['R4-PM12:I'].apply(lambda x: 0 if (x < 2.9) else x)
    synthetic_data['R4:DF'] = synthetic_data['R4:DF'].apply(lambda x: 0 if (x < 0.01 and x > -0.01) else x)

    ###################################################################

    synthetic_data.to_csv("Power_grid_synthetic_data_post_processed.csv")
