# from sdmetrics.reports.single_table import DiagnosticReport
import numpy as np
import pandas as pd
from sdmetrics.single_column import BoundaryAdherence, KSComplement, RangeCoverage, StatisticSimilarity, CSTest
from sdmetrics.single_table import BNLikelihood

if __name__ == '__main__':
    print("evaluating the single column similarities ")
    real_data = pd.read_csv('Power_grid_real_data.csv').reset_index(drop=True)
    synthetic_data = pd.read_csv("Power_grid_synthetic_data.csv").sample(len(real_data))
    # Extra column generated by pandas
    del synthetic_data['Unnamed: 0']
    ##################################################
    # mean value of all rows are calculated
    scores_ks = []
    scores_boundary = []
    scores_range = []
    scores_stat = []
    scores_cs = []
    for i in range(128):
        col = real_data.columns[i]
        scores_ks.append(KSComplement.compute(real_data=real_data[col], synthetic_data=synthetic_data[col]))
        scores_boundary.append(BoundaryAdherence.compute(real_data=real_data[col], synthetic_data=synthetic_data[col]))
        scores_range.append(RangeCoverage.compute(real_data=real_data[col], synthetic_data=synthetic_data[col]))
        scores_stat.append(StatisticSimilarity.compute(real_data=real_data[col], synthetic_data=synthetic_data[col]))
        if (i in [116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]):
            scores_cs.append(CSTest.compute(real_data=real_data[col], synthetic_data=synthetic_data[col]))

    print("KSComplement", np.nanmean(scores_ks))
    print("BoundaryAdherence", np.nanmean(scores_boundary))
    print("RangeCoverage", np.nanmean(scores_range))
    print("StatisticSimilarity", np.nanmean(scores_stat))
    print("CS test", np.nanmean(scores_cs))

    print("BNlikelihood test", BNLikelihood.compute(
        real_data=real_data[real_data.columns[[116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]]],
        synthetic_data=synthetic_data[
            real_data.columns[[116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]]]
    ))
